---
app:
  port: 4000
  host: "0.0.0.0"
  name: "simple-pruduct-api"
  version: "1.0.0"
  environment: "TEST"

mongoDB:
  name: "mongodb"
  user: "user"
  password: "1234"
  host: mongodb
  protocol: mongodb
  db: prod
  url: "mongodb://mongodb:27017/public"
  port: "27017"

importer:
  productCsvUrl: "https://api.frw.co.uk/feeds/all_listings.csv"
  batchSize: 100
